export type Position = 'QB' | 'RB' | 'WR' | 'TE'

export interface Player {
  id: string
  rank: number
  name: string
  position: Position
  team: string
  gamesPlayed: number
  headshotUrl?: string

  // Passing stats
  attempts?: number
  completions?: number
  passingYards?: number
  passingTDs?: number
  interceptions?: number

  // Rushing stats
  carries?: number
  rushingYards?: number
  rushingTDs?: number

  // Receiving stats
  targets?: number
  receptions?: number
  receivingYards?: number
  receivingTDs?: number

  // Calculated
  fantasyPoints: number
  pointsPerGame: number
}

export const mockPlayers: Player[] = [
  // QBs
  {
    id: '1',
    rank: 1,
    name: 'Josh Allen',
    position: 'QB',
    team: 'BUF',
    gamesPlayed: 16,
    passingYards: 4306,
    passingTDs: 35,
    interceptions: 14,
    rushingYards: 524,
    rushingTDs: 7,
    fantasyPoints: 398.2,
    pointsPerGame: 24.9,
  },
  {
    id: '2',
    rank: 2,
    name: 'Jalen Hurts',
    position: 'QB',
    team: 'PHI',
    gamesPlayed: 15,
    passingYards: 3858,
    passingTDs: 23,
    interceptions: 15,
    rushingYards: 760,
    rushingTDs: 13,
    fantasyPoints: 389.5,
    pointsPerGame: 26.0,
  },
  {
    id: '3',
    rank: 3,
    name: 'Patrick Mahomes',
    position: 'QB',
    team: 'KC',
    gamesPlayed: 17,
    passingYards: 4839,
    passingTDs: 37,
    interceptions: 13,
    rushingYards: 358,
    rushingTDs: 4,
    fantasyPoints: 387.1,
    pointsPerGame: 22.8,
  },
  {
    id: '4',
    rank: 4,
    name: 'Lamar Jackson',
    position: 'QB',
    team: 'BAL',
    gamesPlayed: 16,
    passingYards: 3678,
    passingTDs: 25,
    interceptions: 9,
    rushingYards: 821,
    rushingTDs: 5,
    fantasyPoints: 368.4,
    pointsPerGame: 23.0,
  },

  // RBs
  {
    id: '5',
    rank: 5,
    name: 'Christian McCaffrey',
    position: 'RB',
    team: 'SF',
    gamesPlayed: 16,
    carries: 272,
    rushingYards: 1459,
    rushingTDs: 14,
    receptions: 67,
    receivingYards: 564,
    receivingTDs: 7,
    fantasyPoints: 376.3,
    pointsPerGame: 23.5,
  },
  {
    id: '6',
    rank: 6,
    name: 'Austin Ekeler',
    position: 'RB',
    team: 'LAC',
    gamesPlayed: 17,
    carries: 204,
    rushingYards: 915,
    rushingTDs: 13,
    receptions: 107,
    receivingYards: 722,
    receivingTDs: 5,
    fantasyPoints: 346.7,
    pointsPerGame: 20.4,
  },
  {
    id: '7',
    rank: 7,
    name: 'Saquon Barkley',
    position: 'RB',
    team: 'NYG',
    gamesPlayed: 16,
    carries: 295,
    rushingYards: 1312,
    rushingTDs: 10,
    receptions: 57,
    receivingYards: 338,
    receivingTDs: 1,
    fantasyPoints: 285.0,
    pointsPerGame: 17.8,
  },
  {
    id: '8',
    rank: 8,
    name: 'Derrick Henry',
    position: 'RB',
    team: 'TEN',
    gamesPlayed: 16,
    carries: 349,
    rushingYards: 1538,
    rushingTDs: 13,
    receptions: 33,
    receivingYards: 214,
    receivingTDs: 2,
    fantasyPoints: 282.2,
    pointsPerGame: 17.6,
  },
  {
    id: '9',
    rank: 9,
    name: 'Tony Pollard',
    position: 'RB',
    team: 'DAL',
    gamesPlayed: 17,
    carries: 252,
    rushingYards: 1007,
    rushingTDs: 9,
    receptions: 39,
    receivingYards: 371,
    receivingTDs: 3,
    fantasyPoints: 257.8,
    pointsPerGame: 15.2,
  },

  // WRs
  {
    id: '10',
    rank: 10,
    name: 'Justin Jefferson',
    position: 'WR',
    team: 'MIN',
    gamesPlayed: 17,
    targets: 184,
    receptions: 128,
    receivingYards: 1809,
    receivingTDs: 8,
    fantasyPoints: 308.9,
    pointsPerGame: 18.2,
  },
  {
    id: '11',
    rank: 11,
    name: 'Tyreek Hill',
    position: 'WR',
    team: 'MIA',
    gamesPlayed: 17,
    targets: 170,
    receptions: 119,
    receivingYards: 1710,
    receivingTDs: 7,
    fantasyPoints: 290.0,
    pointsPerGame: 17.1,
  },
  {
    id: '12',
    rank: 12,
    name: 'Stefon Diggs',
    position: 'WR',
    team: 'BUF',
    gamesPlayed: 17,
    targets: 154,
    receptions: 108,
    receivingYards: 1429,
    receivingTDs: 11,
    fantasyPoints: 285.9,
    pointsPerGame: 16.8,
  },
  {
    id: '13',
    rank: 13,
    name: 'Davante Adams',
    position: 'WR',
    team: 'LV',
    gamesPlayed: 17,
    targets: 180,
    receptions: 100,
    receivingYards: 1516,
    receivingTDs: 14,
    fantasyPoints: 285.6,
    pointsPerGame: 16.8,
  },
  {
    id: '14',
    rank: 14,
    name: 'CeeDee Lamb',
    position: 'WR',
    team: 'DAL',
    gamesPlayed: 17,
    targets: 181,
    receptions: 107,
    receivingYards: 1359,
    receivingTDs: 9,
    fantasyPoints: 269.9,
    pointsPerGame: 15.9,
  },
  {
    id: '15',
    rank: 15,
    name: 'Amon-Ra St. Brown',
    position: 'WR',
    team: 'DET',
    gamesPlayed: 17,
    targets: 151,
    receptions: 106,
    receivingYards: 1161,
    receivingTDs: 6,
    fantasyPoints: 244.1,
    pointsPerGame: 14.4,
  },

  // TEs
  {
    id: '16',
    rank: 16,
    name: 'Travis Kelce',
    position: 'TE',
    team: 'KC',
    gamesPlayed: 17,
    targets: 150,
    receptions: 110,
    receivingYards: 1338,
    receivingTDs: 12,
    fantasyPoints: 277.8,
    pointsPerGame: 16.3,
  },
  {
    id: '17',
    rank: 17,
    name: 'Mark Andrews',
    position: 'TE',
    team: 'BAL',
    gamesPlayed: 12,
    targets: 86,
    receptions: 58,
    receivingYards: 654,
    receivingTDs: 5,
    fantasyPoints: 165.4,
    pointsPerGame: 13.8,
  },
  {
    id: '18',
    rank: 18,
    name: 'TJ Hockenson',
    position: 'TE',
    team: 'MIN',
    gamesPlayed: 12,
    targets: 95,
    receptions: 66,
    receivingYards: 519,
    receivingTDs: 3,
    fantasyPoints: 141.9,
    pointsPerGame: 11.8,
  },
  {
    id: '19',
    rank: 19,
    name: 'George Kittle',
    position: 'TE',
    team: 'SF',
    gamesPlayed: 15,
    targets: 93,
    receptions: 60,
    receivingYards: 765,
    receivingTDs: 2,
    fantasyPoints: 158.5,
    pointsPerGame: 10.6,
  },
  {
    id: '20',
    rank: 20,
    name: 'Dallas Goedert',
    position: 'TE',
    team: 'PHI',
    gamesPlayed: 15,
    targets: 89,
    receptions: 55,
    receivingYards: 702,
    receivingTDs: 3,
    fantasyPoints: 147.2,
    pointsPerGame: 9.8,
  },

  // More QBs
  {
    id: '21',
    rank: 21,
    name: 'Joe Burrow',
    position: 'QB',
    team: 'CIN',
    gamesPlayed: 17,
    passingYards: 4475,
    passingTDs: 35,
    interceptions: 12,
    rushingYards: 257,
    rushingTDs: 5,
    fantasyPoints: 362.0,
    pointsPerGame: 21.3,
  },
  {
    id: '22',
    rank: 22,
    name: 'Dak Prescott',
    position: 'QB',
    team: 'DAL',
    gamesPlayed: 17,
    passingYards: 4516,
    passingTDs: 37,
    interceptions: 10,
    rushingYards: 282,
    rushingTDs: 6,
    fantasyPoints: 358.4,
    pointsPerGame: 21.1,
  },

  // More RBs
  {
    id: '23',
    rank: 23,
    name: 'Josh Jacobs',
    position: 'RB',
    team: 'LV',
    gamesPlayed: 17,
    carries: 340,
    rushingYards: 1653,
    rushingTDs: 12,
    receptions: 53,
    receivingYards: 400,
    receivingTDs: 0,
    fantasyPoints: 277.3,
    pointsPerGame: 16.3,
  },
  {
    id: '24',
    rank: 24,
    name: 'Nick Chubb',
    position: 'RB',
    team: 'CLE',
    gamesPlayed: 17,
    carries: 302,
    rushingYards: 1525,
    rushingTDs: 12,
    receptions: 27,
    receivingYards: 174,
    receivingTDs: 2,
    fantasyPoints: 269.9,
    pointsPerGame: 15.9,
  },

  // More WRs
  {
    id: '25',
    rank: 25,
    name: 'AJ Brown',
    position: 'WR',
    team: 'PHI',
    gamesPlayed: 17,
    targets: 145,
    receptions: 88,
    receivingYards: 1496,
    receivingTDs: 11,
    fantasyPoints: 263.6,
    pointsPerGame: 15.5,
  },
  {
    id: '26',
    rank: 26,
    name: 'Garrett Wilson',
    position: 'WR',
    team: 'NYJ',
    gamesPlayed: 17,
    targets: 147,
    receptions: 83,
    receivingYards: 1103,
    receivingTDs: 4,
    fantasyPoints: 214.3,
    pointsPerGame: 12.6,
  },

  // More TEs
  {
    id: '27',
    rank: 27,
    name: 'Evan Engram',
    position: 'TE',
    team: 'JAX',
    gamesPlayed: 17,
    targets: 113,
    receptions: 73,
    receivingYards: 766,
    receivingTDs: 4,
    fantasyPoints: 169.6,
    pointsPerGame: 10.0,
  },
  {
    id: '28',
    rank: 28,
    name: 'Pat Freiermuth',
    position: 'TE',
    team: 'PIT',
    gamesPlayed: 16,
    targets: 85,
    receptions: 63,
    receivingYards: 732,
    receivingTDs: 2,
    fantasyPoints: 145.2,
    pointsPerGame: 9.1,
  },
]

// Available seasons for dropdown
export const availableSeasons = [
  { year: 2024, label: '2024 Season' },
  { year: 2023, label: '2023 Season' },
  { year: 2022, label: '2022 Season' },
  { year: 2021, label: '2021 Season' },
  { year: 2020, label: '2020 Season' },
]
